### ISSUE TITLE
Reproducible crashes

### ISSUE THREAD

**Issue by s-fong** [opencor/opencor#1630]
Two different ways to crash OpenCOR using [fast_na_BG_6.zip](https://github.com/opencor/opencor/files/1953994/fast_na_BG_6.zip):
- [x] First way:
  - Run .sedml file - don't wait for it to complete, as it probably won't.
  - While running, open corresponding .cellml file in new tab and modify the code.
  - On saving cellml file, crash should occur.
- [x] Second way:
  - Run .sedml file to completion (i.e. 1000s)
  - When done, change the ending point time to 10s
  - Run simulation again - don't click anything else
  - Reload from File menu - crash should occur.
- [x] Third way:
  - Open the `noble_1962_local.sedml` using the `Simulation Experiment` view
  - In the the SED-ML file, using some external editor, replace `<color>#800002</color>` in the `curve3_1` curve's line with `<color>`
  - Save the SED-ML file and agree to reloading it.
- [x] Fourth way:
  - Run the SED-ML file
  - Switch to the `Raw SED-ML` view and edit the SED-ML file
  - Save the SED-ML file (while still in the `Raw SED-ML` view)

**Comment by s-fong** [comment]
Second crash:
1. Run .sedml file to completion
2. When done, increase the ending point time 
3. run simulation again - don't click anything else
4. Reload from File menu - crash should occur.
[fast_na_BG_6_2.zip](https://github.com/opencor/opencor/files/1949813/fast_na_BG_6_2.zip)

**Comment by agarny** [comment]
Thanks @s-fong, I can (unfortunately) confirm the crash using your first set of steps. Now, just hoping that it will be "easy" to fix... once and for all...

**Comment by dbrnz** [comment]
Thinking more about this, isn't the crux of the problem the fact that `CellmlFile` has created a `CellmlFileRuntime` when really it is `Simulation` that must create the runtime??

A CellML file may well be modified, reloaded, etc, etc all while a simulation is running...

**Comment by agarny** [comment]
> @agarny, I think I know the reason for the "First way" crash above. I'm not sure why there is a tick against it as I can repeatedly reproduce the crash in both your issue1630 branch as well as in master.

There is a tick because everything now works fine in that respect using my [`issue1630` branch](https://github.com/agarny/opencor/tree/issue1630). So, yes, I am a bit surprised that it's not working for you. (FWIW, I have just tried it again and, indeed, everything now works as expected.)

> As I see things, the reason is that `SedmlFile::reset()` deletes `mCellmlFile` which in turn deletes its runtime, which calls `CellmlFileRuntime::reset()`, which then deletes `mCompilerEngine`. Deleting the compiler engine deletes `mExecutionEngine` -- however the running simulation has `mComputeRates` and other functions embedded in the execution engine...
> 
> Does this make sense??

Yes, it does.

> Thinking more about this, isn't the crux of the problem the fact that `CellmlFile` has created a `CellmlFileRuntime` when really it is `Simulation` that must create the runtime??
> 
> A CellML file may well be modified, reloaded, etc, etc all while a simulation is running...

The thing is that we might want the runtime to be used by other parts of OpenCOR besides `Simulation`, which is the reason `CellmlFile` creates a `CellmlFileRuntime`, so that it can be shared with whoever needs a runtime, not to mention that generating a runtime (through the CellML API) is time consuming (but things should be much faster using `libCellML`). Now, I do see your point and maybe a call to `CellmlFile::runtime()` should always create a new `CellmlFileRuntime`, which then becomes the responsibility of the caller to delete at some point?... Ok, I am going to look into it...

**Comment by dbrnz** [comment]
Hmm, I reproducibly crash, even with current HEAD of your [issue 1630](https://github.com/agarny/opencor/tree/issue1630) branch. Which is good, as otherwise things would have been more difficult to track down.

I came to my conclusions because:
1. When running under `lldb`, an exception occurs in `ComputeRates` when it is called by the solver during the simulation.
2. When running without a debugger, the macOS crash reporter reports an exception when `llvm::X86TargetMachine` is deleted as a result of deleting our compiler engine.

What else, besides a simulation, uses a `CellmlFileRuntime`? Or is it that a runtime contains other information than that used by a simulation? In which case would it be better to put the simulation/execution specific parts into a new class, owned by the simulation??

**Comment by agarny** [comment]
> Hmm, I reproducibly crash, even with current HEAD of your [issue 1630](https://github.com/agarny/opencor/tree/issue1630) branch. Which is good, as otherwise things would have been more difficult to track down.

I really don't understand how it can crash in your case since now a simulation is stopped before doing anything (e.g. reloading a SED-ML file). So, no crash should ever occur anymore. Can you confirm that, in `CentralWidget::reloadFile()`, you have something that reads (line 984):

```
// Before we can actually reload the file, we need to make sure
// that the corresponding simulation, if any, has been stopped

if (mSimulationInterface)
    mSimulationInterface->stop(fileName, false);
```

> I came to my conclusions because:
> 1. When running under `lldb`, an exception occurs in `ComputeRates` when it is called by the solver during the simulation.
> 2. When running without a debugger, the macOS crash reporter reports an exception when `llvm::X86TargetMachine` is deleted as a result of deleting our compiler engine.

I can indeed confirm those crash reports using the `master` branch.

> What else, besides a simulation, uses a `CellmlFileRuntime`? Or is it that a runtime contains other information than that used by a simulation? In which case would it be better to put the simulation/execution specific parts into a new class, owned by the simulation?? 

At this point, only `Simulation` uses a `CellmlFileRuntime`, but this might change in the future, who knows. What do you mean by "simulation/execution specific parts"?

**Comment by dbrnz** [comment]
> I really don't understand how it can crash in your case since now a simulation is stopped before doing anything (e.g. reloading a SED-ML file). So, no crash should ever occur anymore. Can you confirm that, in CentralWidget::reloadFile(), you have something that reads (line 984):

I indeed have this code:

![screen shot 2018-05-03 at 10 11 50 am](https://user-images.githubusercontent.com/239220/39551843-cf0943d2-4eba-11e8-863d-31117e8d0004.png)

> At this point, only Simulation uses a CellmlFileRuntime, but this might change in the future, who knows. What do you mean by "simulation/execution specific parts"?

I was wondering if their are things in CellmlFileRuntime that were used by other things besides a simulation.

I've also been under the assumption that unless manually paused/stopped, a simulation always ran to completion (or error), even if its underlying CellML file was being edited -- i.e. a multitasking model, with snapshots created when things are run (and future, with automatic file versioning and attaching provenance information to the simulation).

**Comment by agarny** [comment]
@dbrnz: FWIW, I have just reworked `CellmlFile::runtime()` method, so that it now returns a new runtime every single time. Then, I 'disabled' the following code in `CentralWidget::reloadFile()`:

```
if (mSimulationInterface)
    mSimulationInterface->stop(fileName, false);
```

From there, I was still able to reproduce the first crash. However, using the debugger, the crash now occurs when trying to keep track of the simulation data:

![screen shot 2018-05-03 at 10 34 26 am](https://user-images.githubusercontent.com/602265/39552509-a4fc42c6-4ebd-11e8-8d62-cb4e52daf33c.png)

So, to rework `CellmlFile::runtime()` is not good enough and I am not sure I want to spend more time in that direction. I believe my code in `CentralWidget::reloadFile()` really ought to make the difference and it certainly does on my machine. So, if anything, I would try to understand why it doesn't work on yours...

**Comment by agarny** [comment]
> I was wondering if their are things in CellmlFileRuntime that were used by other things besides a simulation.

No, not at this stage. A `Simulation` is really the only place where a runtime is being used (besides in our CellML tests).

> I've also been under the assumption that unless manually paused/stopped, a simulation always ran to completion (or error), even if its underlying CellML file was being edited -- i.e. a multitasking model, with snapshots created when things are run (and future, with automatic file versioning and attaching provenance information to the simulation).

No, it's not like this at this stage and for the reasons I gave above (i.e. it can take "time" to generate a runtime and we might want a runtime to be used by something else in the future, e.g. if we have another type of Simulation view).

**Comment by dbrnz** [comment]
A simulation is being run in a separate worker thread and having `SimulationWorker::stop()` call `mThread->quit()` is no guarantee that the thread stops running exactly then and there...

**Comment by agarny** [comment]
> A simulation is being run in a separate worker thread and having `SimulationWorker::stop()` call `mThread->quit()` is no guarantee that the thread stops running exactly then and there... 

Agreed, this is why we also have `mThread->wait()` to ensure that it does then and there. That being said, it's still done in the simulation worker thread, as opposed to the main (GUI) thread. Hmm...

**Comment by agarny** [comment]
Ok, I have modified `Simulation::reload()` to stop a simulation, if needed, and it all seems to work fine (with my reworked version of `CellmlFile::runtime()`). I agree that it makes more sense that way, so I am going to double check things and use that approach (thanks for the suggestion!) and remove my `Simulation` interface.

**Comment by dbrnz** [comment]
Great that it all seems to work! I'll test your issue1630 branch as soon as it has the changes.

**Comment by agarny** [comment]
Ok @dbrnz, feel free to have a go... (Fingers crossed! :))

**Comment by dbrnz** [comment]
Still crashing... 👎

I'll do further debugging if you want to put this aside for a bit, given that I've got an environment in which things crash, though it won't be until late this afternoon.

**Comment by agarny** [comment]
@dbrnz, are you just using my [`issue1630` branch](https://github.com/agarny/opencor/tree/issue1630) or are you applying it to your Python branch? If the latter, it would be interesting to see what you get with just the former.

Anyway, I am going to move onto the second crash for now.

**Comment by dbrnz** [comment]
@agarny, the culprit is:
```
    // Get a (new) runtime, if possible

    delete mRuntime;
```
in `Simulation::retrieveFileDetails()`.

This is because `Simulation::save()` doesn't stop the simulation... Would it not be best to stop any running simulation in `retrieveFileDetails()`? And BTW, why not combine `save()` and `reload()`??

**Comment by dbrnz** [comment]
> @dbrnz, are you just using my issue1630 branch or are you applying it to your Python branch? If the latter, it would be interesting to see what you get with just the former.

I'm just using your issue1630 branch.

**Comment by agarny** [comment]
> This is because `Simulation::save()` doesn't stop the simulation... Would it not be best to stop any running simulation in `retrieveFileDetails()`? And BTW, why not combine `save()` and `reload()`??

Oops, my bad indeed! Thanks for not trying to reproduce exactly the first crash above! :)

How do you mean combine `save()` and `reload()`? They are doing slightly different things and we don't want `save()` to stop a simulation. So, probably best to keep them separated.

Anyway, I am going to update `Simulation::retrieveFileDetails()`...

**Comment by agarny** [comment]
Well, it would involve an extra call and a few more tests, so not sure it's really worth it. Anyway, I have updated the code, so hopefully things should be fine at your end. Let me know when you have a minute.

**Comment by dbrnz** [comment]
Still crashing and it is still because the simulation worker has not been stopped...

This time, `SimulationExperimentViewPlugin::fileSaved()` results in `SimulationExperimentViewSimulationWidget::initialize()` being called that then causes the simulation's results to be reset. Meanwhile the worker thread is adding points...

**Comment by agarny** [comment]
Argh! I guess that, whenever I ask a simulation to stop, I should get the GUI thread to wait for the simulation thread to be finished before the GUI threads does anything else. Ok, I am going to look into it and then ask you to test again for me since our machines are different enough (e.g. CPU) that stopping the simulation thread doesn't have the exact same effect on your computer and mine.

**Comment by dbrnz** [comment]
Hmm, a very similar issue to having Python run a simulation and not returning back to Python until the simulation had finished. My solution:

```
// In class constructor
    mSimulationRunEventLoop(new QEventLoop())
...

void SimulationSupportPythonWrapper::simulationFinished(const qint64 &pElapsedTime)
{
    mElapsedTime = pElapsedTime;

    QMetaObject::invokeMethod(mSimulationRunEventLoop, "quit", Qt::QueuedConnection);
}

...

// In run()
        // Signal our event loop when the simulation has finished

        connect(pSimulation, &Simulation::stopped,
                this, &SimulationSupportPythonWrapper::simulationFinished);

        // Start the simulation and wait for it to complete

        if (pSimulation->run())
            mSimulationRunEventLoop->exec();

**Comment by dbrnz** [comment]
> Argh! I guess that, whenever I ask a simulation to stop, I should get the GUI thread to wait for the simulation thread to be finished before the GUI threads does anything else.

Are you certain that `stop()` is being called, as I'm not seeing the `qDebug()` message I put into `SimulationWorker::stop()`.

**Comment by agarny** [comment]
Well, in `Simulation::reload()`, we have a call to `stop(false)` (i.e. `Simulation::stop()`), which will call `SimulationWorker::stop()` if we have a worker, which in turn ask its thread to stop if it is running or paused. So...?

**Comment by dbrnz** [comment]
But my `qDebug()` traces show `Simulation::save()` being called, not `reload()`...

**Comment by agarny** [comment]
I am lost. Can you tell me exactly what you did to get `Simulation::save()` called?

**Comment by agarny** [comment]
> Or rather, I saved a modified SEDML file while its simulation was running.

Ok, that's what I thought and what I wanted to double check with you. :)

Now, it's normal for the simulation not to be stopped if you save the SED-ML file while a simulation is running. However, what is not normal is for you to get a crash at that point. Looking at your trace, `Simulation::save()` correctly calls `Simulation::retrieveFileDetails()`, but `Simulation::retrieveFileDetails()` shouldn't destroy your `CellmlFileRuntime` since `false` is passed to `Simulation::retrieveFileDetails()`, which means that your `CellmlFileRuntime` shouldn't be deleted and recreated.

So, are you up-to-date with my [`issue1630` branch](https://github.com/agarny/opencor/tree/issue1630)? In other words, does your branch contain commit a309360?

**Comment by dbrnz** [comment]
I do have your latest commit:

![screen shot 2018-05-03 at 2 33 55 pm](https://user-images.githubusercontent.com/239220/39557935-139defba-4edf-11e8-8f84-2882c37e1845.png)

The current crash though has nothing to do with `CellmlFileRuntime`. As per my earlier comment:
> ... it is still because the simulation worker has not been stopped...

> This time, SimulationExperimentViewPlugin::fileSaved() results in SimulationExperimentViewSimulationWidget::initialize() being called that then causes the simulation's results to be reset. Meanwhile the worker thread is adding points...

And unlike `reload()`, `Simulation::save()` does not stop the worker...

**Comment by agarny** [comment]
Oh, ok, got it now. It's true that `SimulationExperimentViewWidget::fileSaved()` will call `SimulationExperimentViewWidget::fileReloaded()` if the simulation widget is hidden, in which case the simulation should indeed be stopped before actually calling `SimulationExperimentViewWidget::fileReloaded()`. Ok, I am going to look into it...

**Comment by agarny** [comment]
Ok, @dbrnz, you might want to give it another try...

**Comment by agarny** [comment]
Note that I might still need (and should) handle the termination of a simulation thread properly. I am going to look into it using something like your solution, i.e.

```
// In class constructor
    mSimulationRunEventLoop(new QEventLoop())
...

void SimulationSupportPythonWrapper::simulationFinished(const qint64 &pElapsedTime)
{
    mElapsedTime = pElapsedTime;

    QMetaObject::invokeMethod(mSimulationRunEventLoop, "quit", Qt::QueuedConnection);
}

...

// In run()
        // Signal our event loop when the simulation has finished

        connect(pSimulation, &Simulation::stopped,
                this, &SimulationSupportPythonWrapper::simulationFinished);

        // Start the simulation and wait for it to complete

        if (pSimulation->run())
            mSimulationRunEventLoop->exec();
```

**Comment by dbrnz** [comment]
I still have a crash, although the good news is that it doesn't appear to be related to the worker thread.  What causes it is the call to `runtime->cellmlFile()->xmlBase()`  in `SimulationResults::createDataStore()` -- it looks as if `mModel` hasn't been initialised...

```
Process 88303 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000000000000
error: memory read failed for 0x0
Target 0: (OpenCOR) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x0000000000000000
    frame #1: 0x000000010bcebbd8 libCellMLSupport.dylib`OpenCOR::CellMLSupport::CellmlFile::xmlBase(this=0x0000000118b33eb0) at cellmlfile.cpp:1008
    frame #2: 0x00000001147ffcda libSimulationSupport.dylib`OpenCOR::SimulationSupport::SimulationResults::createDataStore(this=0x0000000116a603f0) at simulation.cpp:573
    frame #3: 0x0000000114800e22 libSimulationSupport.dylib`OpenCOR::SimulationSupport::SimulationResults::reset(this=0x0000000116a603f0) at simulation.cpp:667
    frame #4: 0x000000011462201e libSimulationExperimentView.dylib`OpenCOR::SimulationExperimentView::SimulationExperimentViewSimulationWidget::clearSimulationResults(this=0x0000000118b07d60, pCheckSimulationResults=false) at simulationexperimentviewsimulationwidget.cpp:1363
    frame #5: 0x0000000114621496 libSimulationExperimentView.dylib`OpenCOR::SimulationExperimentView::SimulationExperimentViewSimulationWidget::initialize(this=0x0000000118b07d60, pReloadingView=true) at simulationexperimentviewsimulationwidget.cpp:923
    frame #6: 0x000000011462d517 libSimulationExperimentView.dylib`OpenCOR::SimulationExperimentView::SimulationExperimentViewSimulationWidget::fileReloaded(this=0x0000000118b07d60) at simulationexperimentviewsimulationwidget.cpp:1249
    frame #7: 0x00000001146521c5 libSimulationExperimentView.dylib`OpenCOR::SimulationExperimentView::SimulationExperimentViewWidget::fileReloaded(this=0x0000000114e4d1e0, pFileName=0x00007ffeefbfd1f8) at simulationexperimentviewwidget.cpp:364
    frame #8: 0x0000000114652115 libSimulationExperimentView.dylib`OpenCOR::SimulationExperimentView::SimulationExperimentViewWidget::fileSaved(this=0x0000000114e4d1e0, pFileName=0x00007ffeefbfd1f8) at simulationexperimentviewwidget.cpp:350

(lldb) f 1
frame #1: 0x000000010bcebbd8 libCellMLSupport.dylib`OpenCOR::CellMLSupport::CellmlFile::xmlBase(this=0x0000000118b33eb0) at cellmlfile.cpp:1008
   1005	{
   1006	    // Return our base URI
   1007	
-> 1008	    if (load()) {
   1009	        ObjRef<iface::cellml_api::URI> baseUri = mModel->xmlBase();
   1010	
   1011	        return QString::fromStdWString(baseUri->asText());

(lldb) p mModel
(ObjRef<iface::cellml_api::Model>) $0 = (mPtr = 0x0000000000000000)
```


```

**Comment by dbrnz** [comment]
Yes, I still crash with commit ce19ce3, exactly as in my last comment.

**Comment by agarny** [comment]
Argh, it was wishful thinking, I guess. I still don't understand how you are getting those crashes though. I am just not able to reproduce them on my machine. Would you mind telling me exactly what you are doing?

**Comment by dbrnz** [comment]
I start running the SED-ML simulation, then switch to the SED-ML edit view, change something (a line's colour), and save using ⌘S.

**Comment by agarny** [comment]
Ah, ok! Now, I can indeed reproduce your crash and I do get the same as you.

**Comment by dbrnz** [comment]
Great! 👍

**Comment by agarny** [comment]
Ok, I believe it should be fixed by commit fe30413. At least, it's now fine for me.

**Comment by dbrnz** [comment]
Also works for me 👍 Next is the second way of crashing (that I can also reproduce...).

**Comment by agarny** [comment]
Phew! I should have asked you your exact steps (for the fourth crash) from the beginning. That would have said both of us quite a bit of time, I think. Anyway, onto the second crash tomorrow.

In the end, the decoupling of the simulation side of things from the `Simulation Experiment` view plugin has been proving more complex than I originally anticipated. Still, I believe we are (finally and at long last) getting there.

**Comment by dbrnz** [comment]
I thought I was just following Shelley's recipe, and because it started with opening and running a SED-ML file, I assumed that it was the SED-ML file that was to be edited and saved... And of course my first lot of crashes were to do with sharing of data between threads, for which we must have a robust solution as differences in system timing and load can randomly bite!

I've just had a quick think about the second crash after looking at a stack trace, and suspect the cause is that `GraphPanelWidget::GraphPanelPlotGraphRun`'s sample data has disappeared as a result of resetting the simulation (which deletes the data store). Does this make sense?

**Comment by dbrnz** [comment]
I suspect `GraphPanelPlotGraph::removeRuns()` must be called before simulation results are reset...

**Comment by dbrnz** [comment]
All good for me 👍 👍

**Comment by dbrnz** [comment]
A minor tidy @agarny, but I notice that `src/plugins/support/SimulationSupport/src/simulation.h` declares `doStop()` that is no longer in `simulation.cpp`.

**Comment by agarny** [comment]
Argh, I thought I had removed it, but clearly not. I wish compilers would spot that kind of mistake. Anyway, consider it fixed in the master branch in a minute or so.
